version: "3.2"

services:

  functions-node-18:
    image: functions-node-18
    build:
      context: .
      dockerfile: ./docker/functions-node-18/Dockerfile
    command: /bin/true

  storage-account:
    image: azurite
    build:
      context: ./docker/azurite
      dockerfile: ./Dockerfile
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002

  function:
    image: fn
    env_file:
      - env.example
    build:
      context: .
      dockerfile: ./docker/functions/Dockerfile
    ports:
      - ${FUNCTION_PORT}:7071
    links:
      - storage-account
    depends_on:
      - functions-node-18
